---
  - name: Create a directory mysql in backup
    ansible.builtin.file:
      path: /home/backup/mysql
      state: directory
      owner: backup
      group: backup
      mode: '0755'

  - name: Create MySQL user backup
    community.mysql.mysql_user:
      name: "{{ mysql_backup_user }}"
      password: "{{ mysql_backup_password }}"
      host: "%"
      priv: "agama.*:LOCK TABLES,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Import cnf file to backup folder
    template:
      src: .my.cnf.j2
      dest: /home/backup/.my.cnf
      owner: backup
      mode: '0700'
    notify: Restart mysql service

  - name: Mysql backup in cron
    template:
      src: mysql-backup.j2
      dest: /etc/cron.d/mysql-backup

  - name: Ensure that cron file is created
    file:
      path: /etc/cron.d/mysql-backup
      owner: root
      mode: '0755'
      state: file
