---
  - name: Install nginx
    apt:
        name: nginx
        state: latest
        update_cache: yes

  - name: Copy config
    template:
      src: default.j2
      dest: /etc/nginx/sites-enabled/default
    notify: Restart nginx service

  - name: Start nginx
    service:
        name: nginx
        state: started
        enabled: yes
