---
  - name: Install nginx
    apt:
        name: nginx
        state: latest
        update_cache: yes

  - name: Copy config
    copy:
      src: /home/aleksandr/ansible/ica0002/roles/nginx/files/default
      dest: /etc/nginx/sites-enabled/default
    notify: Restart nginx service

  - name: Start nginx
    service:
        name: nginx
        state: started
        enabled: yes
