---
  - name: Add apt key for influxDB
    ansible.builtin.apt_key:
      url: https://repos.influxdata.com/influxdb.key

  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://repos.influxdata.com/ubuntu focal stable

  - name: Install InfluxDB
    apt:
      name: 
        - influxdb

  - name: Start and enable influxdb
    ansible.builtin.service:
      name: influxdb
      state: started
      enabled: yes

  - name: Install Telegraf
    apt:
      name: telegraf

  - name: influxdb configuration
    copy:
      src: influxdb.conf
      dest: /etc/influxdb/influxdb.conf
    notify: Restart influxdb

  - name: Reconfigure Telegraf
    copy:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
    notify: Restart Telegraf

  - name: Start service Influxdb
    service:
      name: influxdb
      state: started
      enabled: yes

  - name: Start service Telegraf
    service:
      name: telegraf
      state: started
      enabled: yes
