---
  - name: Add a key
    apt_key:
      url: https://packages.grafana.com/gpg.key

  - name: Install tools for Grafana
    apt:
      name: apt-transport-https
      state: latest

  - name: Add Grafana repository
    apt_repository:
      filename: grafana
      repo: deb https://packages.grafana.com/oss/deb stable main

  - name: Install Grafana
    apt:
      name: grafana
      state: latest
    notify: Reset Grafana password

  - name: Start grafana
    service:
        name: grafana-server
        state: started
        enabled: yes

  - name: Reconfigure Grafana
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
    notify: Restart Grafana

  - name: Datasource sample
    template:
      src: sample.yaml.j2
      dest: /etc/grafana/provisioning/datasources/sample.yaml
    notify: Restart Grafana
  
  - name: Dashboard template
    template:
      src: dashboard.yaml.j2
      dest: /etc/grafana/provisioning/dashboards/sample.yaml
    notify: Restart Grafana

  - name: Setup dashboards
    copy:
      src: main.json
      dest: /etc/grafana/provisioning/dashboards/main.json
    notify: Restart Grafana
    
