---
  - name: Create grafana directories
    file:
      path: /opt/grafana/provisioning/{{ item }}
      state: directory
      recurse: yes
    loop: 
      - dashboards
      - datasources

  - name: Put telegraf.yaml to datasources
    template:
      src: telegraf.yaml.j2
      dest: /opt/grafana/provisioning/datasources/telegraf.yaml

  - name: Put influxdb.yaml to datasources
    template:
      src: influx.yaml.j2
      dest: /opt/grafana/provisioning/datasources/influx.yaml

  - name: Put prometheus.yaml to datasources
    template:
      src: prometheus.yaml.j2
      dest: /opt/grafana/provisioning/datasources/prometheus.yaml

  - name: Put dashboard.yaml to dashboards
    template:
      src: dashboard.yaml.j2
      dest: /opt/grafana/provisioning/dashboards/dashboard.yaml

  - name: Put dashboard files to dashboards
    copy:
      src: "{{ item }}"
      dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
    loop: 
      - main.json
      - mysql.json
      - syslog.json

  - name: Put grafana config
    template:
      src: grafana.ini.j2
      dest: /opt/grafana/grafana.ini
    no_log: true

  - name: Install and start the grafana in the docker
    community.docker.docker_container:
      name: grafana
      image: grafana/grafana
      container_default_behavior: no_defaults
      published_ports: "{{ grafana_port }}:3000"
      restart_policy: always
      volumes: /opt/grafana:/etc/grafana
