---
  - name: Intall uwsgi
    apt:
      name:
        - uwsgi
        - uwsgi-plugin-python3

  - name: Start service
    service:
      name: uwsgi
      state: started
      enabled: yes

  - name: Copy the uwsgi config file
    template:
      src: ../templates/agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    notify: Restart uwsgi
