---
  - name: Create a login user
    ansible.builtin.user:   
      name: backup
      state: present
      createhome: yes
      home: /home/backup
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/backup/.ssh/id_rsa
