---
  - name: Install mysql server
    apt:
      name: mysql-server
      update_cache: yes
  
  - name: Install pymysql
    apt:
      name: python3-pymysql
      update_cache: yes

  - name: Start mysql server
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Copy mysql config and restart mysql server
    template:
      src: override.cnf.j2
      dest: /etc/mysql/mysql.conf.d/override.cnf
    notify: Restart mysql

  - name: MySQL database 
    community.mysql.mysql_db:
      name: "{{ mysql_database }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock  

  - name: Create database user with privileges
    community.mysql.mysql_user:
      name: "{{ mysql_user }}"
      host: "%"
      password: "{{ mysql_password }}"
      priv: "{{ mysql_database }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: Create replication MySQL user
    community.mysql.mysql_user:
      name: "{{ mysql_replication_user }}"
      password: "{{ mysql_replication_pass }}"
      host: "%"
      priv: "*.*:REPLICATION SLAVE"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: true

  - name: Read only mode on replica server
    community.mysql.mysql_variables:
      variable: read_only
      value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
      mode: persist
      login_unix_socket: /var/run/mysqld/mysqld.sock
    notify:
      - Reset MySQL source
      - Reset MySQL replica

