---
  - name: Install curl
    apt:
      name: curl
      state: latest

  - name: Install fping
    apt:
      name: fping
      state: latest

  - name: Add the user "pinger"
    user:
      name: pinger

  - name: Create pinger configuration directory
    file:
      path: /etc/pinger
      state: directory
      mode: '0751'

  - name: Import pinger configuration
    template:
      src: pinger.conf.j2
      dest: /etc/pinger/pinger.conf
    notify: Restart pinger

  - name: Change script location
    template:
      src: pinger.sh.j2
      dest: /usr/local/bin/pinger
      mode: '0777'
    notify: Restart pinger

  - name: Create pinger service
    template:
      src: pinger.service.j2
      dest: /etc/systemd/system/pinger.service
    notify: 
      - Reload systemd
      - Restart pinger

  - name: Execute handlers
    meta: flush_handlers

  - name: Start pinger
    service:
      name: pinger
      state: started
      enabled: yes
