---
  - name: Install Prometheus
    apt:
      name: 
        - prometheus

  - name: Configure Prometheus
    template: 
      src: ../templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: 
      - Restart Prometheus
      - Restart Nginx
    become: yes

  - name: Make prometheus available
    template:
      src: prometheus
      dest: /etc/default/prometheus
    notify: 
      - Restart Prometheus
      - Restart Nginx
    become: yes
