---
- name: Install bind
  apt:
    name: bind9 
    update_cache: yes

- name: Start service bind9
  service:
    name: bind9
    state: started

- name: Copy named config file
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Copy named conf local file
  template:
    src: ../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local     
  notify: restart bind9

- name: Copy the resolv file
  template:
    src: ../templates/resolv.conf
    dest: /etc/resolv.conf
  notify: restart bind9

- name: Copy the template
  template:
    src: ../templates/db.example
    dest: /etc/bind/db.efiffel.ttu
  notify: restart bind9
